### signup user
POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "Acme",
    "fullname": "Team Alice",
    "email": "Alice@123.com",
    "password": "hunter42"
}

### signup user
POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "Acme",
    "fullname": "Team Meng",
    "email": "Meng@123.com",
    "password": "hunter42"
}

### signin user

# @name sigin

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "Meng@123.com",
    "password": "hunter42"
}

@token = {{sigin.response.body.token}}


### signin user -> password failed
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "Meng@123.com",
    "password": "hunter42"
}

### create chat
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Acme",
    "members": [1, 2],
    "public": false
}

### get chat list
GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}

### get user list
GET http://localhost:6688/api/users
Authorization: Bearer {{token}}

### upload files

POST http://localhost:6688/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="hello.txt"
Content-Type: text/plain

Hello, World!
--MyBoundary--

### get files
GET http://localhost:6688/api/files/1/005/efb/4c143b8d531411ecd78f2effa226bfd24d.txt
Authorization: Bearer {{token}}

###
POST http://localhost:6688/api/chats/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "Hello World!",
    "files": []
}

### get messages
GET http://localhost:6688/api/chats/1/messages?limit=6&last_id=5
Authorization: Bearer {{token}}
