### signup user1

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "fullname": "TeamMeng",
    "workspace": "acme",
    "email": "TeamMeng@123.com",
    "password": "123456"
}

### signin user1 (valid)
# @name siginin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "TeamMeng@123.com",
    "password": "123456"
}

### Set token variable
@token = {{siginin.response.body.token}}

### signup user2

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "fullname": "TeamZhang",
    "workspace": "acme",
    "email": "TeamZhang@123.com",
    "password": "123456"
}

### signin user2 (valid)
# @name siginin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "TeamZhang@123.com",
    "password": "123456"
}

### Set token variable
@token = {{siginin.response.body.token}}

### create chat
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "acme",
    "members": [1, 2],
    "public": false
}

### get chat api
GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}

### get user list
GET http://localhost:6688/api/users
Authorization: Bearer {{token}}

### upload files
POST http://localhost:6688/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="hello.txt"
Content-Type: text/plain

Hello, World!
--MyBoundary--

### get files
GET http://localhost:6688/api/files/1/0a0/a9f/2a6772942557ab5355d76af442f8f65e01.txt
Authorization: Bearer {{token}}
